"""Add InspectionDetail model

Revision ID: 69a4239eb084
Revises: ad7594d932ba
Create Date: 2026-04-08 14:46:53.130984

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '69a4239eb084'
down_revision = 'ad7594d932ba'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('inspection_details',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('expense_id', sa.Integer(), nullable=False),
    sa.Column('workshop', sa.String(length=200), nullable=True),
    sa.Column('odometer', sa.Integer(), nullable=True),
    sa.Column('expiration_date', sa.Date(), nullable=True),
    sa.Column('notify_before_expiry', sa.Boolean(), nullable=True),
    sa.Column('notify_days_before', sa.Integer(), nullable=True),
    sa.Column('notification_sent', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['expense_id'], ['expenses.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('inspection_details')
    # ### end Alembic commands ###
