"""add theme and username request fields to user

Revision ID: 8b635645f41d
Revises: 1adeb7fc0658
Create Date: 2026-04-07 13:43:42.278010

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8b635645f41d'
down_revision = '1adeb7fc0658'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('theme', sa.String(length=10), nullable=False, server_default='light'))
        batch_op.add_column(sa.Column('pending_username', sa.String(length=80), nullable=True))
        batch_op.add_column(sa.Column('pending_username_at', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('pending_username_at')
        batch_op.drop_column('pending_username')
        batch_op.drop_column('theme')

    # ### end Alembic commands ###
