"""toll expiry date, expiry notifications

Revision ID: a8e39716f2b2
Revises: 8b635645f41d
Create Date: 2026-04-08 10:58:55.023231

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a8e39716f2b2'
down_revision = '8b635645f41d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('insurance_details', schema=None) as batch_op:
        batch_op.add_column(sa.Column('notify_before_expiry', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('notify_days_before', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('notification_sent', sa.Boolean(), nullable=True))

    with op.batch_alter_table('toll_details', schema=None) as batch_op:
        batch_op.add_column(sa.Column('expiration_date', sa.Date(), nullable=True))
        batch_op.add_column(sa.Column('notify_before_expiry', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('notify_days_before', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('notification_sent', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('toll_details', schema=None) as batch_op:
        batch_op.drop_column('notification_sent')
        batch_op.drop_column('notify_days_before')
        batch_op.drop_column('notify_before_expiry')
        batch_op.drop_column('expiration_date')

    with op.batch_alter_table('insurance_details', schema=None) as batch_op:
        batch_op.drop_column('notification_sent')
        batch_op.drop_column('notify_days_before')
        batch_op.drop_column('notify_before_expiry')

    # ### end Alembic commands ###
