"""car visibility: hidden_from_shared, user_car_hidden

Revision ID: ad7594d932ba
Revises: a8e39716f2b2
Create Date: 2026-04-08 12:16:35.958497

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ad7594d932ba'
down_revision = 'a8e39716f2b2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_car_hidden',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('car_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['car_id'], ['cars.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('car_id', 'user_id')
    )
    with op.batch_alter_table('cars', schema=None) as batch_op:
        batch_op.add_column(sa.Column('hidden_from_shared', sa.Boolean(), nullable=False, server_default=sa.false()))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('cars', schema=None) as batch_op:
        batch_op.drop_column('hidden_from_shared')

    op.drop_table('user_car_hidden')
    # ### end Alembic commands ###
